# Generated by Django 4.2.6 on 2023-10-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='default', max_length=50, verbose_name='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(default='https://placehold.co/400', max_length=500, verbose_name='https://placehold.co/400'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='total_available',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
